import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

/// Minimal WebView to display a hosted checkout URL and intercept a deep link.
///
/// - Loads [checkoutUrl].
/// - Intercepts navigation to [returnDeepLink].
/// - When intercepted, pops and passes the full [Uri] to [onReturn].
class CheckoutWebView extends StatefulWidget {
  /// Hosted checkout URL (generated by your backend using PhonePe server APIs).
  final String checkoutUrl;

  /// Custom return deep link (e.g. `myapp://payment-return`).
  final String returnDeepLink;

  /// Callback with the intercepted deep link (including query params).
  final ValueChanged<Uri> onReturn;

  /// Optional AppBar title.
  final String? appBarTitle;

  /// Creates a [CheckoutWebView].
  const CheckoutWebView({
    super.key,
    required this.checkoutUrl,
    required this.returnDeepLink,
    required this.onReturn,
    this.appBarTitle,
  });

  @override
  State<CheckoutWebView> createState() => _CheckoutWebViewState();
}

class _CheckoutWebViewState extends State<CheckoutWebView> {
  late final WebViewController _controller;
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onPageStarted: (_) => setState(() => _loading = true),
          onPageFinished: (_) => setState(() => _loading = false),
          onNavigationRequest: (req) {
            if (req.url.startsWith(widget.returnDeepLink)) {
              widget.onReturn(Uri.parse(req.url));
              if (mounted) Navigator.of(context).pop();
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.parse(widget.checkoutUrl));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.appBarTitle ?? 'PhonePe Checkout')),
      body: Stack(
        children: [
          WebViewWidget(controller: _controller),
          if (_loading)
            const Align(
              alignment: Alignment.topCenter,
              child: LinearProgressIndicator(minHeight: 2),
            ),
        ],
      ),
    );
  }
}
